name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Crear antenv e instalar dependencias
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: .

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Setear version en DEV
        uses: azure/appservice-settings@v1
        with:
          app-name: 'app-cicd-demo-santinoaa-dev'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
          app-settings-json: '[{"name": "APP_VERSION", "value": "${{ github.sha }}"}]'

      - name: Deploy a DEV
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-cicd-demo-santinoaa-dev'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
          package: .

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Setear version en PROD
        uses: azure/appservice-settings@v1
        with:
          app-name: 'app-cicd-demo-santinoaa'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          app-settings-json: '[{"name": "APP_VERSION", "value": "${{ github.sha }}"}]'

      - name: Deploy a PROD
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-cicd-demo-santinoaa'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .